### ISSUE TITLE
Balance issue in Block explorer

### ISSUE THREAD

**Issue by ubiubi18** [rgex/Ubic-Network#1]
There is no balance shown for that ubic-account with expired passport in August 2019: https://ubic.network/addresses/qXuuMAoNsyUppztroqTuT2bJJLbuZMXCX/

**Comment by rgex** [comment]
The bug is fixed, I run 2 explorers it works on this one. http://51.15.67.218/addresses/qXuuMAoNsyUppztroqTuT2bJJLbuZMXCX/

I will have to resync the other one. The bug was already fixed in the core code in august.
Thanks for reporting it :)
